name: Checks

on: [push]

jobs:
  test-lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.Docker.DOCKERHUB_USER }}
          password: ${{ secrets.Docker.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull
        run: docker-compose pull
      - name: Test
        run: docker-compose run web python manage.py test
      - name: Push
        run: docker-compose push
